FROM openjdk:8u171-jdk-stretch

WORKDIR /code
EXPOSE 8080

ENTRYPOINT java -jar /code/run.jar


#CMD java -jar countries-assembly-1.0.1.jar
#ENTRYPOINT ["java", "-jar", "countries-assembly-1.0.1.jar"]
